# Generated by Django 5.2.12 on 2026-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='last_collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wastecollection',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='household',
            index=models.Index(fields=['project', 'last_collection_date'], name='core_househ_project_b15ece_idx'),
        ),
        migrations.AddIndex(
            model_name='wastecollection',
            index=models.Index(fields=['date'], name='core_wastec_date_7dfc6a_idx'),
        ),
        migrations.AddIndex(
            model_name='wastecollection',
            index=models.Index(fields=['project', 'date', 'household'], name='core_wastec_project_9d689e_idx'),
        ),
    ]
