# Generated by Django 5.2.12 on 2026-04-07 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_household_last_collection_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterHousehold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(max_length=50)),
                ('sub_route', models.CharField(blank=True, max_length=200)),
                ('driver_name', models.CharField(blank=True, max_length=200)),
                ('area_name', models.CharField(blank=True, max_length=200)),
                ('hh_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('date_of_active', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='household',
            name='core_househ_project_1e9eb1_idx',
        ),
        migrations.RemoveIndex(
            model_name='wastecollection',
            name='core_wastec_project_9d689e_idx',
        ),
        migrations.AlterField(
            model_name='wastecollection',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterhousehold',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_households', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='masterhousehold',
            index=models.Index(fields=['project', 'is_active'], name='core_master_project_c54244_idx'),
        ),
        migrations.AddIndex(
            model_name='masterhousehold',
            index=models.Index(fields=['house_id'], name='core_master_house_i_e08738_idx'),
        ),
        migrations.AddIndex(
            model_name='masterhousehold',
            index=models.Index(fields=['project', 'area_name'], name='core_master_project_17e1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='masterhousehold',
            index=models.Index(fields=['project', 'driver_name'], name='core_master_project_8f13c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='masterhousehold',
            unique_together={('house_id', 'project')},
        ),
    ]
